# Generated by Django 3.2.9 on 2021-12-14 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.AddField(
            model_name='university',
            name='top_worldwide',
            field=models.PositiveIntegerField(default=2, unique=True, verbose_name='Место в мире'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_country', to='universities.country', verbose_name='Страна расположения'),
        ),
    ]
