# Generated by Django 3.2.9 on 2021-12-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_auto_20211215_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='top_worldwide',
            field=models.PositiveIntegerField(null=True, verbose_name='Место в мире'),
        ),
    ]
