# Generated by Django 3.2.9 on 2021-12-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_alter_university_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='deadline_ed',
            field=models.CharField(max_length=100, verbose_name='Окончание приема заявок на early decision'),
        ),
        migrations.AlterField(
            model_name='university',
            name='deadline_rd',
            field=models.CharField(max_length=100, verbose_name='Окончание приема заявок regular decision'),
        ),
    ]
