# Generated by Django 3.2.9 on 2021-12-14 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_auto_20211215_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_category', to='universities.category', verbose_name='Тип университета'),
        ),
        migrations.AlterField(
            model_name='university',
            name='deadline_rd',
            field=models.CharField(max_length=100, verbose_name='Окончание приема заявок на regular decision'),
        ),
        migrations.AlterField(
            model_name='university',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовать?'),
        ),
    ]
