# Generated by Django 3.2.9 on 2021-12-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_remove_university_top_worldwide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='body',
            field=models.CharField(max_length=1000, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='university',
            name='deadline_ed',
            field=models.CharField(default='-', max_length=100, verbose_name='Окончание приема заявок на early decision'),
        ),
        migrations.AlterField(
            model_name='university',
            name='deadline_rd',
            field=models.CharField(default='-', max_length=100, verbose_name='Окончание приема заявок на regular decision'),
        ),
        migrations.AlterField(
            model_name='university',
            name='url',
            field=models.URLField(null=True, verbose_name='Ссылка на официальный сайт'),
        ),
    ]
