# Generated by Django 3.2.9 on 2021-12-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0008_auto_20211217_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='GPA',
            field=models.FloatField(default=0, null=True, verbose_name='рекомендованый средний балл в школе '),
        ),
        migrations.AlterField(
            model_name='university',
            name='IELTS',
            field=models.FloatField(default=0, null=True, verbose_name='рекомендованый балл по IELTS'),
        ),
        migrations.AlterField(
            model_name='university',
            name='SAT',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='рекомендованый балл по SAT'),
        ),
        migrations.AlterField(
            model_name='university',
            name='TOEFL',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='рекомендованый балл по TOEFL'),
        ),
        migrations.AlterField(
            model_name='university',
            name='deadline_ed',
            field=models.CharField(default='-', max_length=100, null=True, verbose_name='Окончание приема заявок на early decision'),
        ),
        migrations.AlterField(
            model_name='university',
            name='deadline_rd',
            field=models.CharField(default='-', max_length=100, null=True, verbose_name='Окончание приема заявок на regular decision'),
        ),
    ]
